# 1 异常处理

## 1.1 异常处理的思想与程序实现

**异常处理的基本思想**

![](https://github.com/Mozart482/CS-Notes/blob/main/C%2B%2B%E8%AF%AD%E8%A8%80%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1/images/%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E7%9A%84%E5%9F%BA%E6%9C%AC%E6%80%9D%E6%83%B3.png)

**异常处理的语法**

![](https://github.com/Mozart482/CS-Notes/blob/main/C%2B%2B%E8%AF%AD%E8%A8%80%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1/images/%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E7%9A%84%E8%AF%AD%E6%B3%95.png)

**例12-1 处理除零异常**
```
//12_1.cpp
#include <iostream>
using namespace std;
int divide(int x, int y) {
    if (y == 0)
        throw x;
    return x / y;
}
int main() {
    try {
        cout << "5 / 2 = " << divide(5, 2) << endl;
        cout << "8 / 0 = " << divide(8, 0) << endl;
        cout << "7 / 1 = " << divide(7, 1) << endl;
    } catch (int e) {
        cout << e << " is divided by zero!" << endl;
    }
    cout << "That is ok." << endl;
    return 0;
}
```
**异常接口声明**

* 一个函数显式声明可能抛出的异常，有利于函数的调用者为异常处理做好准备

* 可以在函数的声明中列出这个函数可能抛掷的所有异常类型。
```
例如：void fun() throw(A，B，C，D);
```

* 若无异常接口声明，则此函数可以抛掷任何类型的异常。

* 不抛掷任何类型异常的函数声明如下：
```
void fun() throw();
```


## 1.2 异常处理中的构造与析构

**自动的析构**

* 找到一个匹配的catch异常处理后

  * 初始化异常参数。

  * 将从对应的try块开始到异常被抛掷处之间构造（且尚未析构）的所有对象自动地进行析构。

  * 从最后一个catch处理之后开始恢复执行。

**例12-2 带析构语义的类的C++异常处理**
```
//12_2.cpp
#include <iostream>
#include <string>
using namespace std;
class MyException {
public:
    MyException(const string &message) : message(message) {}
    ~MyException() {}
    const string &getMessage() const { return message; }
private:
    string message;
};

class Demo {
public:
    Demo() { cout << "Constructor of Demo" << endl; }
    ~Demo() { cout << "Destructor of Demo" << endl; }
};
void func() throw (MyException) {
    Demo d;
    cout << "Throw MyException in func()" << endl;
    throw MyException("exception thrown by func()");
}

int main() {
    cout << "In main function" << endl;
    try {
        func();
    } catch (MyException& e) {
        cout << "Caught an exception: " << e.getMessage() << endl;
    } 
    cout << "Resume the execution of main()" << endl;
    return 0;
}
```
运行结果：
```
In main function
Constructor of Demo
Throw MyException in func()
Destructor of Demo
Caught an exception: exception thrown by func()
Resume the execution of main()
```

## 1.3 标准程序库异常处理

**标准异常类的继承关系**

![](https://github.com/Mozart482/CS-Notes/blob/main/C%2B%2B%E8%AF%AD%E8%A8%80%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1/images/%E6%A0%87%E5%87%86%E5%BC%82%E5%B8%B8%E7%B1%BB%E7%9A%84%E7%BB%A7%E6%89%BF%E5%85%B3%E7%B3%BB.png)

**C++标准库各种异常类所代表的异常**

![](https://github.com/Mozart482/CS-Notes/blob/main/C%2B%2B%E8%AF%AD%E8%A8%80%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1/images/C%2B%2B%E6%A0%87%E5%87%86%E5%BA%93%E5%90%84%E7%A7%8D%E5%BC%82%E5%B8%B8%E7%B1%BB%E6%89%80%E4%BB%A3%E8%A1%A8%E7%9A%84%E5%BC%82%E5%B8%B8.png)

**标准异常类的基础**

* exception：标准程序库异常类的公共基类

* logic_error表示可以在程序中被预先检测到的异常

  * 如果小心地编写程序，这类异常能够避免

* runtime_error表示难以被预先检测的异常

**例12-3 三角形面积计算**

* 编写一个计算三角形面积的函数，函数的参数为三角形三边边长a、b、c，可以用Heron公式计算：
```
//12_3.cpp
#include <iostream>
#include <cmath>
#include <stdexcept>
using namespace std;
//给出三角形三边长，计算三角形面积
double area(double a, double b, double c)  throw (invalid_argument)
{
   //判断三角形边长是否为正
    if (a <= 0 || b <= 0 || c <= 0)
        throw invalid_argument("the side length should be positive");
   //判断三边长是否满足三角不等式
    if (a + b <= c || b + c <= a || c + a <= b)
        throw invalid_argument("the side length should fit the triangle inequation");
   //由Heron公式计算三角形面积
    double s = (a + b + c) / 2; 
    return sqrt(s * (s - a) * (s - b) * (s - c));
}
int main() {
    double a, b, c; //三角形三边长
    cout << "Please input the side lengths of a triangle: ";
    cin >> a >> b >> c;
    try {
        double s = area(a, b, c);   //尝试计算三角形面积
        cout << "Area: " << s << endl;
    } catch (exception &e) {
        cout << "Error: " << e.what() << endl;
    }
    return 0;
}
```
* 运行结果1：
```
Please input the side lengths of a triangle: 3 4 5
Area: 6
```
* 运行结果2：
```
Please input the side lengths of a triangle: 0 5 5
Error: the side length should be positive
```
* 运行结果2：
```
Please input the side lengths of a triangle: 1 2 4
Error: the side length should fit the triangle inequation
```
